Adding Footer and Unit Test
zeta-o/coderiosity pull request #14
Opened 2020-10-20 05:55 UTC by joalva18

🔨 Adding footer to the project.
🔨 Adding unit test.

2020-10-20 22:37 UTC, mariovaargas requested changes

2020-10-20 22:37 UTC, mariovaargas commented on src/components/Footer/Footer.js
> +const Footer = () =>{
Review if the component name starts with capital letter or not.

2020-10-20 22:37 UTC, mariovaargas commented on src/components/Footer/footer.test.js
> +      <I18nextProvider i18n={i18n}>
You don't have to use i18n unless you define a variable that contains text in two different languages. Check out you resources.json file in the i18n project folder.

2020-10-21 13:58 UTC, zeta-o approved these changes
App

2020-10-21 14:09 UTC, mariovaargas approved these changes

2020-10-21 14:09 UTC, merged